version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: stockbilling_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1708
      MYSQL_DATABASE: auth_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - stock_network

  auth_service:
    build: ./auth_service
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: "mysql+pymysql://root:1708@mysql/auth_db"
    depends_on:
      - mysql
    networks:
      - stock_network


volumes:
  mysql_data:

networks:
  stock_network:
    driver: bridge